"""add age column to users

Revision ID: 35d81c5fb048
Revises: c52610b8f535
Create Date: 2026-05-18 11:02:17.000692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d81c5fb048'
down_revision: Union[str, Sequence[str], None] = 'c52610b8f535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('strengths', sa.String(), nullable=True))
    op.add_column('students', sa.Column('learning_profile', sa.String(), nullable=True))
    op.add_column('students', sa.Column('preferred_reinforcers', sa.String(), nullable=True))
    op.add_column('students', sa.Column('sensory_triggers', sa.String(), nullable=True))
    op.add_column('students', sa.Column('communication_style', sa.String(), nullable=True))
    op.add_column('students', sa.Column('emotional_regulation_notes', sa.String(), nullable=True))
    op.drop_column('students', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('students', 'emotional_regulation_notes')
    op.drop_column('students', 'communication_style')
    op.drop_column('students', 'sensory_triggers')
    op.drop_column('students', 'preferred_reinforcers')
    op.drop_column('students', 'learning_profile')
    op.drop_column('students', 'strengths')
    # ### end Alembic commands ###
