"""create student professionals table

Revision ID: b85c6e0bf157
Revises: 52c515da6097
Create Date: 2026-05-19 11:39:03.111334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85c6e0bf157'
down_revision: Union[str, Sequence[str], None] = '52c515da6097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_student', sa.Enum('OWNER', 'AEE', 'SUPPORT', 'PSYCHOLOGIST', 'SUPERVISOR', 'VIEWER', name='student_professional_roles'), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_register_aba', sa.Boolean(), nullable=False),
    sa.Column('can_create_assessment', sa.Boolean(), nullable=False),
    sa.Column('can_create_pei', sa.Boolean(), nullable=False),
    sa.Column('can_generate_ai_report', sa.Boolean(), nullable=False),
    sa.Column('can_view_reports', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_professionals_student_id'), 'student_professionals', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_professionals_user_id'), 'student_professionals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_professionals_user_id'), table_name='student_professionals')
    op.drop_index(op.f('ix_student_professionals_student_id'), table_name='student_professionals')
    op.drop_table('student_professionals')
    # ### end Alembic commands ###
