"""create initial schema

Revision ID: db663fde25dc
Revises: 
Create Date: 2026-05-20 19:31:17.827239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db663fde25dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'psychologist', 'supervisor', 'aee', 'support_professional', 'school', 'guardian', name='user_roles'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_phone', sa.String(length=30), nullable=True),
    sa.Column('communication_notes', sa.Text(), nullable=True),
    sa.Column('sensory_notes', sa.Text(), nullable=True),
    sa.Column('general_observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('strengths', sa.String(), nullable=True),
    sa.Column('learning_profile', sa.String(), nullable=True),
    sa.Column('preferred_reinforcers', sa.String(), nullable=True),
    sa.Column('sensory_triggers', sa.String(), nullable=True),
    sa.Column('communication_style', sa.String(), nullable=True),
    sa.Column('emotional_regulation_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('assessment_type', sa.String(length=100), nullable=False),
    sa.Column('assessment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavior_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('antecedent', sa.Text(), nullable=False),
    sa.Column('behavior', sa.Text(), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('strategy_used', sa.Text(), nullable=True),
    sa.Column('strategy_effective', sa.Boolean(), nullable=True),
    sa.Column('environment', sa.String(length=255), nullable=True),
    sa.Column('people_present', sa.Text(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('function_hypothesis', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_student', sa.Enum('OWNER', 'AEE', 'SUPPORT', 'PSYCHOLOGIST', 'SUPERVISOR', 'VIEWER', name='student_professional_roles'), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_register_aba', sa.Boolean(), nullable=False),
    sa.Column('can_create_assessment', sa.Boolean(), nullable=False),
    sa.Column('can_create_pei', sa.Boolean(), nullable=False),
    sa.Column('can_generate_ai_report', sa.Boolean(), nullable=False),
    sa.Column('can_view_reports', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_professionals_student_id'), 'student_professionals', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_professionals_user_id'), 'student_professionals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_professionals_user_id'), table_name='student_professionals')
    op.drop_index(op.f('ix_student_professionals_student_id'), table_name='student_professionals')
    op.drop_table('student_professionals')
    op.drop_table('behavior_records')
    op.drop_table('assessments')
    op.drop_table('ai_reports')
    op.drop_table('students')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
